### Create Product (Valid)
POST http://localhost:3000/products
Content-Type: application/json

{

  "title": "Apple Watch Series 9",
  "description": "Latest Apple Watch with advanced features",
  "quantity": 5,
  "totalPrice": 120000.00,
  "totalDiscount": 8000.00
}

### Get All Products (Default)
GET http://localhost:3000/products

### Get All Products (Page 1, Limit 2)
GET http://localhost:3000/products?page=1&limit=20

### Get All Products (Page 2, Limit 2)
GET http://localhost:3000/products?page=2&limit=2

### Filter by Title (Apple)
GET http://localhost:3000/products?filter=Apple

### Sort by Price Ascending
GET http://localhost:3000/products?sort=totalPrice&order=ASC

### Sort by Price Descending
GET http://localhost:3000/products?sort=totalPrice&order=DESC

### Update Product
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
  "title": "Updated Product Title",
  "quantity": 5
}

### Soft Delete Product
DELETE http://localhost:3000/products/2

### Restore Product
PATCH http://localhost:3000/products/2/restore
